# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-10-28 03:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0002_auto_20181028_0317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Park',
            fields=[
                ('park_id', models.AutoField(primary_key=True, serialize=False)),
                ('park_name', models.CharField(db_index=True, max_length=32, null=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('created_time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='park_company', to='company.Company')),
            ],
            options={
                'db_table': 'park',
            },
        ),
    ]
