# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-10-28 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='company_time',
            new_name='updated_time',
        ),
        migrations.RemoveField(
            model_name='company',
            name='company_address',
        ),
        migrations.RemoveField(
            model_name='company',
            name='company_size',
        ),
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterModelTable(
            name='company',
            table='company',
        ),
    ]
